# Generated by Django 4.1.2 on 2022-12-09 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nfl_scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(blank=True, default=datetime.datetime.today)),
                ('schedule_season', models.IntegerField(max_length=4)),
                ('schedule_week', models.CharField(max_length=30)),
                ('schedule_playoff', models.BooleanField()),
                ('team_home', models.CharField(max_length=75)),
                ('score_home', models.IntegerField(blank=True, max_length=20)),
                ('score_away', models.IntegerField(blank=True, max_length=20)),
                ('team_away', models.CharField(max_length=75)),
                ('team_favorite_id', models.CharField(blank=True, max_length=4)),
                ('spread_favorite', models.DecimalField(blank=True, decimal_places=1, max_digits=8)),
                ('over_under_line', models.DecimalField(blank=True, decimal_places=1, max_digits=8)),
                ('stadium', models.CharField(blank=True, max_length=50)),
                ('stadium_nuetral', models.BooleanField(blank=True)),
                ('weather_temperature', models.IntegerField(blank=True)),
                ('weather_wind_mph', models.IntegerField(blank=True)),
                ('weather_humidity', models.IntegerField(blank=True)),
                ('weather_detail', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='nfl_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=75)),
                ('team_name_short', models.CharField(max_length=75)),
                ('team_id', models.CharField(max_length=20)),
                ('team_id_pfr', models.CharField(max_length=75)),
                ('team_conference', models.CharField(blank=True, max_length=75)),
                ('team_division', models.CharField(blank=True, max_length=75)),
                ('team_conference_pre2002', models.CharField(blank=True, max_length=75)),
                ('team_division_pre2002', models.CharField(blank=True, max_length=75)),
                ('games', models.ManyToManyField(blank=True, to='superbowlodds.nfl_scores')),
            ],
        ),
    ]
