# Generated by Django 4.1.2 on 2022-12-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbowlodds', '0002_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfl_team',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='choice',
        ),
    ]
